### ISSUE TITLE
Modal Generates Error - Object doesn't support property or method 'modal'

### ISSUE THREAD

**Issue by Shando** [spaghett1c0de/DataTable-AltEditor#1]
I am using DataTables in a Razor Pages application, with Bootstrap 4, and, when I click on the “Edit” button, I get the following error:

> Object doesn't support property or method 'modal'

As far as I can tell, I have included all the relevant .js files in the <head> of my Razor Page _Layout file:

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/autofill/2.3.5/js/dataTables.autoFill.min.js"></script>
    <script src="https://cdn.datatables.net/autofill/2.3.5/js/autoFill.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/colreorder/1.5.2/js/dataTables.colReorder.min.js"></script>
    <script src="https://cdn.datatables.net/fixedcolumns/3.3.1/js/dataTables.fixedColumns.min.js"></script>
    <script src="https://cdn.datatables.net/fixedheader/3.1.7/js/dataTables.fixedHeader.min.js"></script>
    <script src="https://cdn.datatables.net/keytable/2.5.2/js/dataTables.keyTable.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.4/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.4/js/responsive.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/rowgroup/1.1.2/js/dataTables.rowGroup.min.js"></script>
    <script src="https://cdn.datatables.net/rowreorder/1.2.7/js/dataTables.rowReorder.min.js"></script>
    <script src="https://cdn.datatables.net/scroller/2.0.2/js/dataTables.scroller.min.js"></script>
    <script src="https://cdn.datatables.net/searchpanes/1.1.0/js/dataTables.searchPanes.min.js"></script>
    <script src="https://cdn.datatables.net/searchpanes/1.1.0/js/searchPanes.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/select/1.3.1/js/dataTables.select.min.js"></script>
    <script src="~/js/dataTables.altEditor.js"></script> 

The line causing the issue is Line 569 in dataTables.altEditor.js:

`$selector.modal(‘show’);`

According to the debugger 

> $selector.modal

 is “undefined”?

Forgot to add my .cshtml file:

```
<h1>Asset` Type Table</h1>

<p>
    <a asp-page="/BuildStageDeploy/TblAssetType_Create">Create New</a>
</p>

<div class="container">
    <table cellpadding="0" cellspacing="0" border="0" class="dataTable table table-striped" id="table1"></table>
</div>

<style>
    input:invalid {
        border-color: red
    }
</style>

<script>
    $(document).ready(function () {
        var dataSet = @Html.Raw(Json.Serialize(@Model.TblAssetTypes));

        var columnDefs = [{
            data: "Code",
            title: "Code",
            type: "readonly"
        },
        {
            data: "Name",
            title: "Asset Type"
        },
        {
            data: "Active",
            title: "Active"
            }];

        var myTable;

        myTable = $('#table1').DataTable({
            "sPaginationType": "full_numbers",
            data: dataSet,
            idSrc: "Code",
            columns: columnDefs,
            dom: 'Bfrtip',        // Needs button container
            select: 'single',
            responsive: true,
            altEditor: true,     // Enable altEditor
            buttons: [{
                text: 'Add',
                name: 'add'        // do not change name
            },
            {
                extend: 'selected', // Bind to Selected row
                text: 'Edit',
                name: 'edit'        // do not change name
            },
            {
                extend: 'selected', // Bind to Selected row
                text: 'Delete',
                name: 'delete'      // do not change name
            }]
        });
    });
</script>
```
Where the dataset contains json data like this:

{"Code":"SL","Name":"Standard Laptops","Active":false}

**Comment by spaghett1c0de** [comment]
@Shando 
If that's the full list of all the included JS files, then you're missing the **Bootstrap JS**. The _bootstrap.js_ should be included after the _popper.js_. Below is the latest version of the two libraries. 
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

I've also put together a demo in JSFiddle:
https://jsfiddle.net/spaghett1c0de/9mpqej2u/46/

The **Resources** panel on the left shows all the required resource files needed. The demo JS script **starts at line 880** (I had to include the altEditor script inside the demo that way because I tried to include the raw script from Github, it didn't work). Follow a similar setup and you should be good to go.

Please lemme know if this resolves your issue. Also, keep in mind that the minified JS in this repository is not updated so please use the non-minified version. I will update this repository soon with the new minified file and new examples and API documentation updates.

Best,
Vincent

**Comment by Shando** [comment]
Hi Vincent,

Works perfectly now! 

So many <script> tags that I missed an important one! Though, everything else seemed to work fine, so I didn't even think of checking for the Bootstrap js file :(

Thanks for your help

Shando
